travis:
  secure:
    BINSTAR_TOKEN: pV+vEEnZaWZUUyuoWYSictJTPfpmLa4mak7fr4Wj16MS4n5EhZ+vYaLASL1zwmAQurTp3XuJ62c5jDBMKanyXQ5Y/5qIl8zuwLTsNBANLJjifLYkEPLGtxipOzGs+2mwT0EMxLy1USNHOLHeOl0FwTssqCxPPaVDI8HWOoq4wsxQD41VZkitSbgL+dQuxoFtHsOV6AynpxzvnxJ6hJ86O70/fklrq0jgAL8Ao1+FWpx4pDxo09tQkTS+GxSMEKpMpleq0MGfkqZZvaLMgq0r5Dl1QxXJRr1gW+Wzt9EbBgvOgMxy5dburIJazJ8zszc9M9CfO0+J21DQklDVPmiwxRIW7D8zBfGqblz3fRQ2nTYLOCykyYZIYrTajyuA3jPUNbL+gpOxyBtKpXFe+xGR18ZA/vOIJIs5GgzWzo5CpuAM8eRZ0gps2Jn44Zy7QWOpKAqfxWOvioZKODPxvMdhivmYkFGFIKCK4bBJku2maAUvAUxEvWaIMPOG6j59BJntCmoL7D9zIjFSE6VmLYWZIV19fqY6BLpTHDQ2GtRdnKBOL8tV1mPpNOYg9CR60Yh9z3Xv1OZQfRBJ1TsEiM+jYXjlNBbPoqHw1MP1SHcCmE/XvHvi9MJMFAC6cTHIYe/hsToizzC6MRVxw2Z8Wvu+iBIe8BWP/ftD0QK0Oo2rBzI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
