travis:
  secure:
    BINSTAR_TOKEN: jv1xuWlU1nzZRGp1c3lbVNFTuakVKSix03egp5GUuhh6MF7LGWgjeK5VeExvbN7WDWZAyhDGCIadAPPVUB5w2vBbjee/iaqCAvUuXrYcBBLj+uk2+U+EukZIjaqK/BacT8aG7+zKAzRGqTxjeZohyfI4Pnbg1pwDrai8PZ/cuLo6ViqOkpSVOZcTfM9V3fGSNGD1T0EGAOn3oOuL7Vce387vXBLIUhuWARcOJyfIXtEwtCrlOn9FySryhdB5hLlEcbnZZFVwPbP1wNWJW2h7h8MVGtGf9PZT8qrMSxTGDT26+A7xwdof8mkmki57IkJYeNYB6p3j8eZESbEtSVWlGtg54tGo/sBJ5ogIx6a7aeurp5iDKqGT7FM/8mtgpskSueyMbbL1N+gKnjk3u++tZ8EhbTxL/aCUB6Ez8UwG8J8Ptg6B/gfW79Cyo8Cfm1jzmbR8frR7gFMmbCP7Dpzh1dneLidV+Ur6mXHus9t4fomX6rBoOAgo3/usaS+P3CJnTBUrKPFNgKyGf7ZfZzu981XgSPmh6i+Mi5yRkTW2hg8uApTn1E9rg8untDqug8vBUj+fzL5BlmtPtpXbM3cszP33nQ1Zk3YPnAJCUZ07EJPfZm6Cm1S2ly2yJ0tJ4oHYnaIOPHLIiJf0Daflp/7arnXNRodGhs/mrDsRjI3fGEM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
